name: Deploy Website

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'SmartTennisSensor/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: 'SmartTennisSensor'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run predeploy
      - run: npm run deploy
